POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "TestUsername",
    "email" : "Test@email.com",
    "password" : "testpassword"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "TestUsername",
    "password" : "testpassword"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "TestEditUsername",
    "password" : "testpasswordchange"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll